# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - bruki_mammad@mail.ru
    on_success: never # default: change
    on_failure: always # default: al,ways

env:
  global:
    - CODECOV_TOKEN="51efd03c-f06f-4e32-a61e-58ab6279abc6"
    - CODECOV_TOKEN="fbffbd8e-9499-4808-8541-2aabf611a71b"